export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_APPLICATIONS_START = 'FETCH_APPLICATIONS_START';
export const FETCH_APPLICATIONS_FAIL = 'FETCH_APPLICATIONS_FAIL';
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS';

export const PLATFORM_SETTINGS_LOADED = 'PLATFORM_SETTINGS_LOADED';
export const PLATFORM_SETTINGS_LOADED_ERROR = 'PLATFORM_SETTINGS_LOADED_ERROR';
export const PLATFORM_SETTINGS_SAVE = 'PLATFORM_SETTINGS_SAVE';

export const FETCH_USERS_PAGE_START = 'FETCH_USERS_PAGE_START';
export const FETCH_USERS_PAGE_SUCCESS = 'FETCH_USERS_PAGE_SUCCESS';
export const FETCH_USERS_PAGE_FAIL = 'FETCH_USERS_PAGE_FAIL';
